### ISSUE TITLE
My two cents

### ISSUE THREAD

**Issue by ZXT-Tech** [w3x731/survivIoAim#1]
Good work @w3x731 

I would recommend to avoid players inside building (if possible) because it can't shoot over walls.

There is also a problem when two players have the same (or almost) distance and are in the opposite direction, you keep turning around and making useless shots, it should stick to the target (possibly until some key is pressed).

**Comment by w3x731** [comment]
Avoid players inside building are complex task. And search a solution take a long time. That time game code may changed.
Script updated and you can disable it using z key.

**Comment by ZXT-Tech** [comment]
Yes, I thought so about buildings.

The hotkey to enable/disable was totally necessary, anyway I was not talking about that.
I was talking about stick to one target, for example I want it aim a player till he is downed but the current functionality will change the target if we find someone on the road and the distance is less and it's OK but not always effective.

By the way, can you explain how forecastCoeff value works?
Some practical examples are welcome :)

**Comment by ZXT-Tech** [comment]
Thanks for the explanation.
Capture mode is working like a charm 👍
