### ISSUE TITLE
May 10th UPDATE!!!

### ISSUE THREAD

**Issue by TRSO4** [w3x731/survivIoAim#11]
Heyyo
I loved your hack and it worked 100% 
but....
As of the May 10th update in surviv.io your hack no longer works. Surviv somehow managed to counter your hack.  Could you please update it?

**Comment by ZXT-Tech** [comment]
Use the patcher.

**Comment by TRSO4** [comment]
I have

**Comment by TRSO4** [comment]
I might have done something wrong

**Comment by TRSO4** [comment]
OHHH ok I see where I went wrong thx anyway!

**Comment by w3x731** [comment]
Autopatcher released. Now when you load page, code patches automatically. Its would be more reliability. Test it.
