### ISSUE TITLE
Please Listen

### ISSUE THREAD

**Issue by SamuelTheSuperb** [w3x731/survivIoAim#13]
Can you disable the auto pickup for the guns, and maybe have a separate toggle for it?

**Comment by w3x731** [comment]
Yes i can, soon.

**Comment by NOOOOOOO0000000b** [comment]
have a toggle key for roof see through please

**Comment by NOOOOOOO0000000b** [comment]
If you delete  the JS files like the zoom ones, will the zoom hack not work but the hack  will still work?

**Comment by ZXT-Tech** [comment]
@NOOOOOOO0000000b before asking something so simple, why not try it and see if it keeps working?
If it does not work all you have to do is restore the file.

**Comment by SamuelTheSuperb** [comment]
Will you please help it toggles the aim-bot with the zoom for some reason.

**Comment by SamuelTheSuperb** [comment]
Can you make it so the zoom stays when you activate it, so i can have it when i have my aimbot off?

**Comment by SamuelTheSuperb** [comment]
Yes or no?

**Comment by w3x731** [comment]
> Can you make it so the zoom stays when you activate it

Yes

> i can have it when i have my aimbot off?

Stay zoom when you disable cheat?

**Comment by ZXT-Tech** [comment]
He wants the cheat functions to work separately.
For example to use zoom and auto-loot but not aimbot.

IMO it's also the most convenient.

**Comment by w3x731** [comment]
Oh, but its released. `Esc` menu can help.

**Comment by w3x731** [comment]
@SamuelTheSuperb yeah, youre right. I'm add a left shift key listener for fast disabling the aim. Its disabling while you're press.

**Comment by SamuelTheSuperb** [comment]
Thank you, this is a very great project!
