### ISSUE TITLE
character moves automatically

### ISSUE THREAD

**Issue by jerem314** [w3x731/survivIoAim#16]
Hey, this is the first script that I saw working, and it is great, although it has problems for me.
when you try to move, it goes nowhere automatically. I'm trying to move to the other direction in this video but it went to the sea automatically...

![t0m8u-yx4sj](https://user-images.githubusercontent.com/39269948/40279595-21c367a6-5c80-11e8-88f9-3779889d73b8.gif)

**Comment by w3x731** [comment]
Hmm, for me all works fine. Are you tried refresh game tab? Is this problem repeat?

**Comment by jerem314** [comment]
Yes...

**Comment by jerem314** [comment]
To specify my problems, when press 'a' (left) even once, it starts to go in that direction all the way. you can press up and down to go diagonally, but going right rarely works...

**Comment by w3x731** [comment]
I understand you, but i dont know why you see it.
