### ISSUE TITLE
AutoOpeningDoors is closing doors as well

### ISSUE THREAD

**Issue by DragonflyerHD** [w3x731/survivIoAim#17]
Hi there,
your AutoOpeningDoors feature is opening and closing doors when you walk by them which can be very annoying if you want to track down someone.

To fix this, you should change line 28 in autoOpeningDoors.js to:
if(interactionEmitter.scope.hasOwnProperty('door') && !interactionEmitter.scope.door.open) {

**Comment by w3x731** [comment]
You propose only opening doors, without closing?

**Comment by DragonflyerHD** [comment]
Exactly

**Comment by SamuelTheSuperb** [comment]
Can you get rid of the right click to switch guns? The scroll is just as easy and the right click to switch guns stops you from using emotes. D:
