### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by asianhacks** [w3x731/survivIoAim#18]
Hi, I really appreciate this!!! Keep up the great work!! The timely updates are just amazing. You are really the best. I only have one issue and it is the names. If possible could you make the names a toggle so you can see peoples names when you want? 
Thank you so much

**Comment by asianhacks** [comment]
Also, the left click to switch guns is making me unable to send emotes :( If possible make it a toggle on the menu as well!! :)

Thanks!!!! Your the best!!

**Comment by w3x731** [comment]
Ok

**Comment by asianhacks** [comment]
Not fixed yet?
