### ISSUE TITLE
Savesettings

### ISSUE THREAD

**Issue by asianhacks** [w3x731/survivIoAim#24]
Hi, sorry for all my complaining, but this might be the last then it is perfect. The settings that i set will not save when I reload the page so I just have to keep putting it to the settings that I like. It used to work before but now the settings doesnt save.

**Comment by NOOOOOOO0000000b** [comment]
i know right?

**Comment by asianhacks** [comment]
I might not have worded it correctly. When you adjust the settings during a game, then you decide to join your friends game, the link sends you to a different page, then when the game starts, the settings you adjusted before are not saved.

**Comment by w3x731** [comment]
@asianhacks yeah i know what you mean, soon i will do it.

**Comment by zbot473** [comment]
Probably you can write them to chrome.storage or chrome.sync
