### ISSUE TITLE
What is curweaponidx?

### ISSUE THREAD

**Issue by zbot473** [w3x731/survivIoAim#26]
Is this the current weapon?
If not, is there a way to get that?

**Comment by w3x731** [comment]
As i remember, its a index the one of four available weapons (hands, gernades, or first gun or second gun).

**Comment by zbot473** [comment]
Cool thanks. How do i get the game APIs? When I create a new js file i cant access the curweaponidx.

Also, gernades are actually spelled grenade.

**Comment by zbot473** [comment]
Is curweaponidx a string or an int?

**Comment by w3x731** [comment]
@zbot473 If you need access to the game variable just uncomment these lines

https://github.com/w3x731/survivIoAim/blob/21909d024de2fe4792e9541345049e4160f09176/survivIoAimChromeExtension/init.js#L159-L161

**Comment by zbot473** [comment]
I am trying to create a new js file.
