### ISSUE TITLE
Weird

### ISSUE THREAD

**Issue by asianruletheworld** [w3x731/survivIoAim#34]
[Surviv. weird.zip](https://github.com/w3x731/survivIoAim/files/2133449/Surviv.weird.zip)
When ever I activate the hack, or shift to activate then deactivate, the players gun flicks back then fowards, its hard to explain so heres a video.

**Comment by asianruletheworld** [comment]
[filesystem:chrome-extension://mmeijimgabbpbgpdklnllpncmdofkcpn/persistent/707d7a2b-9e40-45ee-y87a-25f4e60763c8.webm](url)

**Comment by asianruletheworld** [comment]
do u have discord so I can send the video over?

**Comment by w3x731** [comment]
Its a really strange. Try to reinstall extension. Please write me if a problem not solved.

**Comment by cornmask** [comment]
Same here, and the issue lingers for some time (back to mouse-oriented aim introduction and maybe even earlier). More accurate, it flicks randomly, usually somewhere in between two directions (original aim and assisted), but sometimes goes to extremietes. Doesnt affect gameplay much, though, as a flick lasts a frame or slightly more.
My guess is that might be something with coordinate prediction parameters reinitializing from legacy values.

**Comment by asianruletheworld** [comment]
yeah it tried installing again but it didnt work @cornmask explained it very well :)

**Comment by w3x731** [comment]
I not see this behaviour on my computer in both extensions. It is in a solo or squad mode? Do you trying to use survivIoAimChromeExtensionManager?

**Comment by cornmask** [comment]
Both extensions, any mode, since long before. Good point, though, i'll perform test on all my systems available and report on the results.

**Comment by w3x731** [comment]
https://nofile.io/f/ZZ98FE105pc

**Comment by w3x731** [comment]
Hmm, i think i know what you mean. When i release left shift, the gun jerks to left direction and back to the enemy. Do you mean that?

**Comment by asianruletheworld** [comment]
yeah exatcly that

**Comment by asianruletheworld** [comment]
@w3x731 found a fix yet?

**Comment by w3x731** [comment]
@asianruletheworld its not critical, im busy now

**Comment by asianruletheworld** [comment]
@w3x731 k whenever u are free, pls fix man!! , (yeah its not that big of a deal soo its honestly ok but:)) Thx for everthing man
