### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by humphreygaming** [w3x731/survivIoAim#37]
surviv updated and now it is patched

**Comment by w3x731** [comment]
By this update game developers apply an obfuscation into client code. Needs too many time to recognize all game variables.

**Comment by humphreygaming** [comment]
ok

**Comment by w3x731** [comment]
Patching in process

**Comment by IceHacks** [comment]
@humphreygaming this is not a competition lol we support each other and learn from each others code.

**Comment by humphreygaming** [comment]
my boy icehaxs. Did not know you payed much attention to other people. And yeah, im aware this is no competition. The dude who was going to make it in under 1 hour failed.
