### ISSUE TITLE
Any Hacks that work?

### ISSUE THREAD

**Issue by MrHaxAlot** [w3x731/survivIoAim#39]
I just want a hack to have a advantage please reply with a link and a tutorial of installation thanks cuz this isnt working

**Comment by w3x731** [comment]
@MrHaxAlot yeah, this not work because im not repair that. Wait, or use other hacks

**Comment by 1tarko** [comment]
@w3x731 do you or anyone else know something that works ? thanks

**Comment by humphreygaming** [comment]
there is no hax that works. Reuke is working on it but it will be available in a week

**Comment by IceHacks** [comment]
Mine works

**Comment by salad1n** [comment]
@IceHacks Yours is not working neither

**Comment by IceHacks** [comment]
@salad1n My newest one, surviv-extension

**Comment by salad1n** [comment]
I followed the instructions but it seems like not working at all

**Comment by salad1n** [comment]
Thank you it's working!

**Comment by MrHaxAlot** [comment]
Thanks Ice Hacks, is there any Spread or Aimbot Hacks?How do you use the zoom in your hack

**Comment by IceHacks** [comment]
Ok @MrHaxAlot the zoom for mine is built-in so 1xScopes are 2xScopes and so on. No aimbots yet. @salad1n Trees have not been programmed in yet. Thanks

**Comment by MrHaxAlot** [comment]
Time has passed, any hacks for aim now?

**Comment by w3x731** [comment]
@MrHaxAlot Aim works now.

**Comment by 1tarko** [comment]
@w3x731 Excellent, first aimbot that works, change the key that shows the map and weapon because they are the same key (Q), and implement the Autoloot. Thanks for the cheat
