### ISSUE TITLE
Doesn't work now

### ISSUE THREAD

**Issue by Pinky574** [w3x731/survivIoAim#47]
This hack doesn't work now after update.
Please fix this.

**Comment by alexvornoffice** [comment]
I played 2 days all day, it how fun, I knew it will stop working soon... so that's why I started to play as much I could... Din not get any ban as now, even with cheats sometimes it is hard to win, but with cheats like 20-30% as was able to win to round in Solo mode.

**Comment by internetjunkiee** [comment]
The hack is patched can you update it .

**Comment by w3x731** [comment]
https://github.com/w3x731/survivIoAim/commit/facf8413c3875317d312e9b358fbc5a30ff03f0f
