### ISSUE TITLE
The Hack was Patched 

### ISSUE THREAD

**Issue by internetjunkiee** [w3x731/survivIoAim#49]
Can you update it please

**Comment by Think-It** [comment]
Really ? Thank you, we did not see the others 3/4 tickets for this problem.

**Comment by internetjunkiee** [comment]
Ur so funny dude you should be a comedian !!!!!
Like really do you really feel fullfilled with your life saying that?

**Comment by Najlepszy56** [comment]
Two more hours and I will upload a working version

**Comment by Think-It** [comment]
Sure. TY.

**Comment by w3x731** [comment]
https://github.com/w3x731/survivIoAim/commit/facf8413c3875317d312e9b358fbc5a30ff03f0f
