### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by miloslavche** [w3x731/survivIoAim#59]
Doesn't work. I'm pressing Z and nothing happenes. Mb problem with autohealing?

**Comment by alexvornoffice** [comment]
no they update the code very often because they want the hack not to work, It is required the hack to be generated automatically everyday so I think is possible because I saw that some variables are renamed after a new patch....

**Comment by miloslavche** [comment]
Is it difficult to change name of all necessary variables to make cheat work again? Mb not for all – only aim, zoom and ceilings. Can I do it by myself?
