### ISSUE TITLE
the game crashes when I try to use the nade

### ISSUE THREAD

**Issue by alexvornoffice** [w3x731/survivIoAim#60]
maybe because of the timer function...

**Comment by w3x731** [comment]
What is nade?

**Comment by player0047** [comment]
nade is a granade ... and when u throw it game freez i heard voice and more...

**Comment by alexvornoffice** [comment]
nade = grenade, I checked the "gernadeTimer.js" file and removed some lines so it will work...
also the file name is not correct...

**Comment by w3x731** [comment]
Thanks
