### ISSUE TITLE
the new surviv mod update doesint work

### ISSUE THREAD

**Issue by GoDzGodHasFaith** [w3x731/survivIoAim#75]
the new update you did for the surviv mod doesint work. When i am in game and press z it doesint enable the hacks. pls fix

**Comment by Najlepszy56** [comment]
https://github.com/w3x731/survivIoAim/pull/77/commits/e516b2e9008315646d014b2de971184bd0c6ff12

**Comment by GoDzGodHasFaith** [comment]
still doesint work

**Comment by GoDzGodHasFaith** [comment]
nvm needed to config with the javascript

**Comment by w3x731** [comment]
Working like a charm for me

**Comment by Najlepszy56** [comment]
No contact, the problem has probably been solved. I close.
