### ISSUE TITLE
An idea

### ISSUE THREAD

**Issue by NOOOOOOO0000000b** [w3x731/survivIoAim#9]
Also, can you make your mouse move too when using your aimbot?

**Comment by OpKibo** [comment]
Can you make people to teleport in one place so that you can kill all of them at once? Or increasing the damage of the guns?

**Comment by SamuelTheSuperb** [comment]
that is an extremely unrealistic feature. plus they would know you were hacking.

**Comment by OpKibo** [comment]
Then, can you increase the damage of the guns? or player esp?

**Comment by w3x731** [comment]
@OpKibo 
Don't know, if i knew a possible way, i did it.

**Comment by OpKibo** [comment]
Then can you add the toggle key for the zoom hack adn the see through hack?

**Comment by w3x731** [comment]
> adn the see through hack?

What does it mean?

**Comment by OpKibo** [comment]
you know how you have the toggle key for the hack,  have toggle keys for the zooming hack and being able to see through hack too.

**Comment by w3x731** [comment]
@OpKibo 
Cant understand what you mean.

**Comment by SamuelTheSuperb** [comment]
if you press z, and press it again, you will have zoom without your aimbot.

**Comment by w3x731** [comment]
But zoom cheat now is not available. The game server, return data about objects around you. And if you dont have a zoom, you can't see what's happening around you.

**Comment by OpKibo** [comment]
how can i only  enable my aimbot?

**Comment by NOOOOOOO0000000b** [comment]
cuz i want to only have my aimbot and remove  the zoom adn the see through hack
Also, client was updated

**Comment by jimbothejambo** [comment]
When do you think the hacks will be updated to the new client?

**Comment by ZXT-Tech** [comment]
Use the patcher.

**Comment by NOOOOOOO0000000b** [comment]
Thank you

**Comment by NOOOOOOO0000000b** [comment]
It lags like hell using the extension

**Comment by NOOOOOOO0000000b** [comment]
how do i remove the zoom? cuz it lags

**Comment by w3x731** [comment]
@NOOOOOOO0000000b 
https://github.com/w3x731/survivIoAim/tree/master/survivIoAimNoZoomExtension

**Comment by jimbothejambo** [comment]
you should add a setting to zoom in and out on the scope like some of the other hacks have, other that that, this extension is great and thank you for all your work!

**Comment by ZXT-Tech** [comment]
@jimbothejambo I'm not sure what you're referring to but if you want get rid of scope in, replace '"1xscope":this.localData.curScope' with 'this.localData.curScope:this.localData.curScope'

**Comment by w3x731** [comment]
Nic, thanks, i do it

**Comment by w3x731** [comment]
Now, minimal absolute scope radius is 8x

**Comment by ZXT-Tech** [comment]
By the way, some good ideas would be:

- Use moveSpread factor to improve aim while we're moving (also shotSpread could be used for better accuracy).

- Auto-pickup/loot (mobile players have this feature, so it could be used).

**Comment by NOOOOOOO0000000b** [comment]
reupload  the aimbot without zoom please

**Comment by w3x731** [comment]
Okay

**Comment by jimbothejambo** [comment]
@ZXT-Tech I mean he should add a feature where you can hold a button and scroll to zoom in and out. Another extension that my friend showed me had this where you can zoom out too see even the whole map (doesn't completely render but still cool)

**Comment by ZXT-Tech** [comment]
@jimbothejambo that's useless now, you would not see more just smaller (what is not useful at all).

**Comment by ZXT-Tech** [comment]
@w3x731 I would suggest add a variable to enable and disable the zoom (enabled by default), since having two versions can be somewhat tricky when updating and who does not want the zoom function enabled should only change it to false.

**Comment by jimbothejambo** [comment]
@w3x731 I agree with ZXT that an auto pickup feature would be cool too and it is used on mobile 
so it probably would be easy to find

**Comment by ZXT-Tech** [comment]
@jimbothejambo then just edit scopeZoomRadius values and try to find max value for each scope.
Anyway you will not be able to see other players out of your radius, it's not very effective or useful.

**Comment by jimbothejambo** [comment]
@w3x731 Is there a way that I can decrease the amount of shaking that the auto aim does and also you should add a line to the person you are targeting

**Comment by ZXT-Tech** [comment]
@jimbothejambo if you want completely transparent ceiling then replace 0.5 with 0 at https://github.com/w3x731/survivIoAim/blob/12c77e3793e570bad06469f970c029f9b58553a1/survivIoAimChromeExtension/survivIoAim.js#L63

**Comment by jimbothejambo** [comment]
Is there a way to stop the player from shaking when it is targeting someone

**Comment by w3x731** [comment]
I believe that way exists

**Comment by w3x731** [comment]
I think that when you pull the trigger, game client send its action on a server and server generate a random shaking for you.

**Comment by w3x731** [comment]
@jimbothejambo it's a good way, im did not guess for this

**Comment by ZXT-Tech** [comment]
@w3x731 two suggestions regarding the latest updates:

- Self-opening door variable and/or a key to enable/disable (you don't always need to open/close the doors automatically).
- Auto loot delay (you can't drop items because at the time you drop them, the auto-loot will take them).

New idea:

- Auto fire for single fire mode weapons holding the mouse button (fists, m9, m9_dual, ot38, ot38_dual,  mk12, m39,deagle, deagle_dual).

**Comment by jimbothejambo** [comment]
@w3x731 look at the extension I attached earlier, or just try it, the auto aim is much more accurate so if you could replace whatever your autoaim is with this one but keep everything else it would be perfect

**Comment by SamuelTheSuperb** [comment]
Can you turn off the auto pickup for the guns? also I don't like the auto door opening that much. Great Hack!

**Comment by jimbothejambo** [comment]
@w3x731  Awesome! You're the best!

**Comment by NOOOOOOO0000000b** [comment]
can you remove the auto door opening and opened ceiling for no zoom aimbot?

**Comment by w3x731** [comment]
@NOOOOOOO0000000b yes i can. Soon

**Comment by NOOOOOOO0000000b** [comment]
thank you

**Comment by NOOOOOOO0000000b** [comment]
so no zoom aimbot only has aimbot, and nothing else

**Comment by NOOOOOOO0000000b** [comment]
is the better aimbot added?

**Comment by SamuelTheSuperb** [comment]
Can you disable the auto pickup for the guns, and maybe have a separate toggle for it?

**Comment by NOOOOOOO0000000b** [comment]
have toggle key for see through roofs please

**Comment by NOOOOOOO0000000b** [comment]
no menu please

**Comment by jimbothejambo** [comment]
I think a menu would be super cool

**Comment by NOOOOOOO0000000b** [comment]
no, then when you use hacks infront of other people, they will know that you are hacking

**Comment by w3x731** [comment]
Hmm, how can they know?

**Comment by NOOOOOOO0000000b** [comment]
they will  be able to look at your menu. Maybe a toggle key for the menu?

**Comment by NOOOOOOO0000000b** [comment]
also, when you use the zoom, can you  make it start from default 1x scope, not 8 scope

**Comment by w3x731** [comment]
@NOOOOOOO0000000b For menu press `Esc` key. Latest commit change start radius to default.

**Comment by NOOOOOOO0000000b** [comment]
okay
thank you

**Comment by NOOOOOOO0000000b** [comment]
is there a toggle key for see through hacks?

**Comment by jimbothejambo** [comment]
Can you make it so you can hold a button and scroll to zoom out as close or far as you want. The extension I attached previously has it and even without the scope you can render pretty far, like with an 8x you can see similar to that with a 15

**Comment by w3x731** [comment]
@jimbothejambo press `Left shift` + `Scroll wheel`

**Comment by w3x731** [comment]
@NOOOOOOO0000000b 

> is there a toggle key for see through hacks?
I still understand what you mean.

**Comment by NOOOOOOO0000000b** [comment]
you know how there isn't a roof

**Comment by NOOOOOOO0000000b** [comment]
esc button doesn't work also

**Comment by w3x731** [comment]
@NOOOOOOO0000000b Press `Z` key to enable the cheat (after starting a round), and `Esc` to show menu.

**Comment by NOOOOOOO0000000b** [comment]
esc doesn't work

**Comment by NOOOOOOO0000000b** [comment]
it shows the other menu

**Comment by NOOOOOOO0000000b** [comment]
now it works

**Comment by NOOOOOOO0000000b** [comment]
wait, is the setting going to be consistent, or do you have to change it everytime

**Comment by w3x731** [comment]
@NOOOOOOO0000000b Try to watch it by himself.

**Comment by jimbothejambo** [comment]
The control and scroll just zooms in and out the gui

**Comment by w3x731** [comment]
@jimbothejambo No control, just left shift + scroll. Please.

**Comment by jimbothejambo** [comment]
@w3x731 That didn't work for me

**Comment by NOOOOOOO0000000b** [comment]
i have a lit idea, what about a grenade time counter

**Comment by NOOOOOOO0000000b** [comment]
also, can u make the file no zoom aimbot extension again? i thought that the menu thingy was confusing

**Comment by NOOOOOOO0000000b** [comment]
for the no zoom aimbot extension, only have the aimbot and the grenade time counter please

**Comment by w3x731** [comment]
@NOOOOOOO0000000b what a problem with menu? When you start new game, press `Z`, after press `Esc` and change options by you need. After press `Esc` again. Options will save while you not reload a page.

**Comment by NOOOOOOO0000000b** [comment]
it is pretty confusing, but have you considered a grenade time counter?

**Comment by NOOOOOOO0000000b** [comment]
i liked it when it was simple, z to activate the hacks

**Comment by SamuelTheSuperb** [comment]
same

**Comment by w3x731** [comment]
I'm busy now, and cant developing the cheat quickly

**Comment by SamuelTheSuperb** [comment]
you should remove this NOOOOOOOOOOOOOOOOOOOOB

**Comment by zbot473** [comment]
I will try and add a grenade timer

**Comment by NOOOOOOO0000000b** [comment]
it doesn't work

**Comment by NOOOOOOO0000000b** [comment]
k
